### ISSUE TITLE
Different experience when using `eslint` directly, or via the Rollup plugin

### ISSUE THREAD

**Issue by akauppi** [TrySound/rollup-plugin-eslint#10]
http://stackoverflow.com/questions/39317999/getting-wrong-line-numbers-with-eslint-and-rollup

Do I need to have a certain version of `eslint` installed, for the plugin? 

Currently have: 

```
$ node_modules/.bin/eslint --version
v3.4.0
```

rollup-plugin-eslint 2.0.2

Symptoms:
- output line numbers are one off of the actual numbers
- the set of rules seems to be different from what I set up in `.eslintrc.js`
- most importantly: changes in the source files are NOT affecting `node_modules/.bin/rollup -c` lint errors, in any way

**Comment by TrySound** [comment]
@akauppi Can you show your rollup config?

**Comment by miroli** [comment]
I have the exact same error. Here is my rollup config.

    import babel from 'rollup-plugin-babel';
    import eslint from 'rollup-plugin-eslint';
    import nodeResolve from 'rollup-plugin-node-resolve';

    export default {
      entry: 'src/js/index.js',
      format: 'iife',
      dest: 'dist/bundle.js',
      plugins: [
        nodeResolve({
          jsnext: true
        }),
        babel({
          exclude: 'node_modules/**'
        }),
        eslint({
          exclude: 'node_modules/**'
        })
      ],
      sourceMap: 'inline'
    };

**Comment by TrySound** [comment]
@miroli Of course you have wrong positions. You are trying to lint babeled code. Order of plugins is important.

**Comment by miroli** [comment]
Wow. Thank you!
