### ISSUE TITLE
Show Total Errors/Warnings

### ISSUE THREAD

**Issue by joshrhoades** [TrySound/rollup-plugin-eslint#12]
This is not an issue, more like a feature request/proposal.

When running eslint via this plugin for a few files, the output is mostly manageable. However, with a  large project there are times when there could be so much output that its hard to track overall improvements to the code from the linter perspective, specifically because all we see in the CLI output is file after file with its individual count of errors/warns scrolling by, with no sense of the total errors, warnings, etc.

I briefly started looking into adding this based on eslint configurations, but haven't had enough time to see what it would take, but this seems like a useful feature to me.

And yes, a project may not need this that often, but after moving my huge library into rollup, then redefining its JS style guide with eslint (migrating from jshint), and up-porting it to ES6, this would have been immensely helpful (still would be, since I am not finished yet).

Thoughts?

**Comment by TrySound** [comment]
It's not quite possible as rollup does not allow to have a state in plugins.
