### ISSUE TITLE
allowTemplateLiterals prop on object in `quotes` doesn't seem to work correctly.

### ISSUE THREAD

**Issue by jakewies** [TrySound/rollup-plugin-eslint#13]
version: 3.0.0

I have my config setup like so inside `eslintrc.json`:

```
{
    "env": {
        "browser": true,
        "es6": true
    },
		"globals": {
	    "ENV": true
	  },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            2
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": ["error", 
                          "single",
                          {
	             		"avoidEscape": true,
				"allowTemplateLiterals": true
			  }
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

In a JS file I have a line of code:

``const toSay = `Hello, ${name}!`; ``

ESlint is erroring out at this line, `Strings must use singlequote`. This could just be a configuration error on my part, but I am following the documentation on the `quotes` [rule](http://eslint.org/docs/rules/quotes) and tracked this error in an @ESLint issue [here](https://github.com/eslint/eslint/issues/5234) and the eventual solution [here](https://github.com/eslint/eslint/pull/5661).

**Comment by TrySound** [comment]
Did you try to run eslint cli for this file?

**Comment by jakewies** [comment]
I have not. I will give it a try when I get home from work.

**Comment by jakewies** [comment]
Looks like there was a text error on my part. No worries. I'll close this issue out. Thanks!
