### ISSUE TITLE
unignore node_modules

### ISSUE THREAD

**Issue by dionysiusmarquis** [TrySound/rollup-plugin-eslint#14]
Hey,

I just wanted to mention that CLIEngine will ignore all packages inside `node_modules` anyway. This will happen here: [cli.isPathIgnored(file)](https://github.com/TrySound/rollup-plugin-eslint/blob/master/src/index.js#L27) and here: [cli.executeOnText(code, file)](https://github.com/TrySound/rollup-plugin-eslint/blob/master/src/index.js#L31)
I thought I could unignore my own lib inside `node_modules` by adding `exclude: []` to my options. Unfortunately CLIEngine will ignore the package anyway. You have to put `!node_modules/package` inside your `.eslintignore` and `include: ['node_modules/package/**']` to your options to get it working.
In the end you can remove ` || 'node_modules/**'` from [options.exclude || 'node_modules/**'](https://github.com/TrySound/rollup-plugin-eslint/blob/master/src/index.js#L14)

Just wanted to point it out in case someone else might try to lint own libs inside `node_modules`

https://github.com/eslint/eslint/issues/5410
[.eslintignoreWithUnignoredDefaults](https://github.com/eslint/eslint/blob/4b7305e2c169196ffb07a4760f6d92465b65e630/tests/fixtures/ignored-paths/.eslintignoreWithUnignoredDefaults)

**Comment by TrySound** [comment]
Why lint inside node_modules?

**Comment by dionysiusmarquis** [comment]
I have linked my own js-lib via `npm link` to `node_modules`. This way i can easily change something inside my own lib. By unignoring my lib i can even lint without switching to my lib project etc.

**Comment by TrySound** [comment]
@dionysiusmarquis Then maybe it shoudn't be separate package? Such process makes your module not quite isolated, Package should take care of itself only.
