### ISSUE TITLE
Change `throwError` to `throwOnError` and `throwOnWarning`

### ISSUE THREAD

**Issue by jonataswalker** [TrySound/rollup-plugin-eslint#16]
@TrySound  would accept a PR to these changes?

The reason is add the ability to not break on warnings for example.

**Comment by TrySound** [comment]
Yep

**Comment by jonataswalker** [comment]
@TrySound still waiting for your help on #17

**Comment by yairEO** [comment]
omg our Build at my workplace failed for 2 days just because `throwError` was set to `true` and somebody forgot adding one single space somewhere in the code and the `jenkins` Build broke because of indentation warning....
