### ISSUE TITLE
Also linting JSON or MD file

### ISSUE THREAD

**Issue by joelchu** [TrySound/rollup-plugin-eslint#2]
In my tag I include external JSON or MD file. And the linter also linting them. How do I stop it? 

Here is my config

     eslint({
			exclude: [
				'node_modules/**',
				'bower_components/**'
			],
			envs: ["browser", "mocha"],
			extensions: ['.js','.tag'],
			parser: "babel-eslint"
		}),

Also I keep getting 

/src/app/components/containers/about.tag
  14:74  error  Parsing error: Unexpected token

Here is the about.tag 

    import readme from '../../../../README.md';
    import '../stateless/display.tag';
    <about>

	<display>
		<h1>About</h1>
	</display>

	<span id="displayMarkdownContent"></span>

	<script>
		this.on('mount' , () =>
		{
			$('#displayMarkdownContent' , this.root).html(markdown.toHTML(readme));
		});

	</script>
      </about>

And a few other tag files with a similar setup. Cheers.

**Comment by TrySound** [comment]
Hi, @joelchu Try to `add **/*.{md,tag}` into excluded list.

**Comment by TrySound** [comment]
@joelchu However I think eslint can't understand `tag` format. Which babel config do you use?

**Comment by joelchu** [comment]
Thanks for the quick answer. 

1. Tried excluded no luck. 
2. Tried eslint-plugin-riot no luck 

I guess I need to write one myself then. 

The code I am working is here https://github.com/joelchu/es6-dev-rollup-riot-demo.git

Thanks again.
