### ISSUE TITLE
Cannot pass globals as option from eslint config file

### ISSUE THREAD

**Issue by markbrouch** [TrySound/rollup-plugin-eslint#20]
When specifying `globals` (https://eslint.org/docs/user-guide/configuring#specifying-globals) the plugin throws the following error:
```
[!] TypeError: (options.globals || []).reduce is not a function
```

This is using the config:
```js
{
  globals: {
    MY_GLOBAL: false
  }
}
```

I suspect this is because the eslint cli engine expects globals to be an array, but the eslint config expects it to be an object. They do not match.

When changing the config to be an array (which is invalid for eslint config), everything works as expected.

The problem here is that a valid eslint config file cannot be used as the config for this plugin.

**Comment by TrySound** [comment]
@markbrouch If you look at the top of [options](https://github.com/TrySound/rollup-plugin-eslint#options) section you will find an answer.

**Comment by markbrouch** [comment]
That confirms my suspicion that CLI Engine expects an Array instead of the config file's expected Object. It would be a nice feature for this plugin to be able to import a config file instead, but in case anybody else runs into this issue here's the workaround I went with:

```js
let eslintConfig = require('./.eslintrc');

eslintConfig = {
  ...eslintConfig,
  globals: Object.keys(eslintConfig.globals),
};

// Then in your rollup config for this plugin:
plugins: [
  eslint(eslintConfig),
]
```

**Comment by TrySound** [comment]
Why not just use config in root directory?

**Comment by markbrouch** [comment]
ESLint's config file expects `global` to be an Object, but the CLI Engine expects it to be an Array, so you can't use the config from root directory without applying the transform on `global` outlined above.

**Comment by TrySound** [comment]
No, I mean you don't need to specify eslint config in rollup config file. Just add `.eslintrc.{js,yml,json}` or `eslintConfig` field in `package.json` and it will be loaded automatically like in any other eslint wrapper.

**Comment by markbrouch** [comment]
Oh awesome, I didn't know you could do that! Thought you had to specify the config as a param in the plugin.

**Comment by TrySound** [comment]
I thought it's common case. Probably it should be mentioned in the docs. Would like to send pull request?
