### ISSUE TITLE
Possible to pass eslint config file?

### ISSUE THREAD

**Issue by bugs181** [TrySound/rollup-plugin-eslint#25]
Is it possible to pass a specific eslint config file using this plugin? Looking through the README and other issues, it does not appear this concern has been raised before.

I have a project that uses different linting rules based on specific files. 
For example, while developing I have es6 rules (and no semi-colons) but when linting on a build directory, I would like to use es5 (and mandatory semi-colons).

Something like:

```
{
  input: 'lib/index.js',
  output: {
    file: 'build/build.js',
    format: 'iife',
  },

  plugins: [
    eslint('config/build.eslintrc.json'),
  ],
}
```

**Comment by bugs181** [comment]
Update: Was able to make this modification to support this feature. Would be willing to send a PR.

```
function eslint(options = {}) {
  if (typeof options === 'string') {
    const configFile = path.resolve(process.cwd(), options)
    options = require(configFile)
  }

...
}
```

**Comment by TrySound** [comment]
@bugs181 Sure. PR welcome

**Comment by bugs181** [comment]
@TrySound any way we can get this PR merged? Any hold ups there?

**Comment by bugs181** [comment]
Closing. Feature is in latest commit.
