### ISSUE TITLE
ES6 Support ? 

### ISSUE THREAD

**Issue by ghost** [TrySound/rollup-plugin-eslint#30]
`import { eslint } from "rollup-plugin-eslint";
         ^^^^^^
SyntaxError: The requested module 'rollup-plugin-eslint' does not provide an export named 'eslint'`

Hey, 
I can't seem to use this on node --experimental-modules. Is it planned to add ES6 support ?

**Comment by TrySound** [comment]
Hi, why do you need this? Rollup out of the box bundles config so you may just use esm. Modules are experimental and they may change so I wouldn't like to introduce them for this specific case.

**Comment by TriMoon** [comment]
@TrySound
Just FYI, JavaScript modules are NOT experimental anymore on the web :wink:
I advice you to follow current tech when creating new code 😉
Besides es6 modules work better 😁

**Comment by TrySound** [comment]
@TriMoon FYI this is node only module. It's not intended to be used on the web.

> Besides es6 modules work better 😁

mjs specifically does not work in a lot of cases like the one from topic. It's not ready for usage in node. [esm loader](https://github.com/standard-things/esm) solves the problem better and does not require any changes from my side.
