### ISSUE TITLE
causing a Rollup error?

### ISSUE THREAD

**Issue by yairEO** [TrySound/rollup-plugin-eslint#5]
After including your code in my Rollup build, I get this error:

```
Rollup:  Cannot read property 'length' of undefined
```

I have no idea in which file, or line.. happen help in any way? Thanks

ps - I think it might be because I use eslint version `2.9.0`

---

 update - had a problem with the installed version of ESLINT, sorry bogdan!

**Comment by TrySound** [comment]
@yairEO Is 2.9 buggy or you had 1.\* version?
