### ISSUE TITLE
Using caching to only lint changed files

### ISSUE THREAD

**Issue by yairEO** [TrySound/rollup-plugin-eslint#6]
without your code, I was using a caching script that only linted files which has changed. does that even (can) work with your Rollup plugin? Thanks

**Comment by TrySound** [comment]
@yairEO Inremental build in our plans.
https://github.com/rollup/rollup/issues/191
https://github.com/rollup/rollup/issues/284
We don't have a lot of time to maintain rollup big features. But if you have some ideas, welcome to discuss.

**Comment by TrySound** [comment]
Incremental build was introduced since the last night. So, i close it.
