### ISSUE TITLE
eslint version

### ISSUE THREAD

**Issue by adriengibrat** [TrySound/rollup-plugin-eslint#9]
I'd like to use eslint 3.0.0...
I thinks the best solution is to put your eslint dependency as a peer dependency, so it's up to the user to choose / upgrade eslint version.

Thought?

**Comment by TrySound** [comment]
Peer dependencies are only pain. So I'll just release major version.

**Comment by adriengibrat** [comment]
Thanks ;)

Why do you think peer dependencies are "only" pain ?

The only change (from a end-user point of view) would be on install:

`npm i -D rollup-plugin-eslint eslint` <- need to explicitly install eslint

IMHO, not a big deal, and then the eslint version used by the package would
be explicit (and may be discovered correctly by CI services like bithound).

**Comment by Calyhre** [comment]
Any news on this? 
I agree on @adriengibrat's point, explicitly install it seems a better way to deal with this.

**Comment by adriengibrat** [comment]
I'm ready for a PR, with updated README ;)

**Comment by TrySound** [comment]
Upgraded to eslint3. Thanks.
https://github.com/TrySound/rollup-plugin-eslint/commit/52240a6ebd2f849ed62c9f2a2cb4e3cbfbf8dc31

**Comment by TrySound** [comment]
Peer dependencies is bad because there could be breaking changes in API and keeping responsibility on users heads is bad practice.

**Comment by adriengibrat** [comment]
Thanks for the update
